<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<h4>Erweiterungen der Accountverwaltung</h4>
<ul>
    <li>Accounterstellung und Verknüpfung an E-Mail Adresse und Passwort (und deren Verwaltung) trennen, sodass weitere Verknüpfungsmöglichkeiten einfacher angebaut werden können</li>
</ul>
<h3>Version 1.7.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Geänderte Pakete</h4>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Clientmessage
                <ul>
                    <li>Umstellung der Records für die beiden Clientmessagequellen auf die neue Recordklasse mit einem Erstellungszeitpunkt</li>
                </ul>
            </li>
            <li>
                Cronjob
                <ul>
                    <li>Umstellung der Records für die Cronjobs auf die neue Recordklasse mit einem Erstellungs- und Änderungszeitpunkt</li>
                    <li>Es ist nun möglich einzelne Cronjobs gezielt auszuführen auch wenn sie zeitlich noch nicht ausgeführt werden sollen</li>
                </ul>
            </li>
            <li>
                Log
                <ul>
                    <li>Umstellung der Records für die Logeinträge auf die neue Recordklasse mit einem Erstellungszeitpunkt</li>
                </ul>
            </li>
            <li>
                Storage
                <ul>
                    <li>Abstrakte Recordklassen hinzugefügt die ein Erstellungs- und Änderungszeitpunkt definieren. Davon abgeleitete Records erhalten beim Speichern in eine Storage Engine automatisch die Zeitpunkte</li>
                    <li>Umstellung der Records für die Pakete auf die neuen Recordklassen sodass nun ersichtlich ist wann ein Paket hinzugefügt und zuletzt aktualisiert wurde</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h2>Migration vom Branch 1.6</h2>
<h3>Benötigt</h3>
<ul>
    <li>Durch die Umstellung der beiden Clientmessagequellen auf die neue Recordklasse mit einem Erstellungszeitpunkt erhält der Client nun bei jeder Clientmessage ihren Erstellungszeitpunkt als 'created' statt als 'timestamp'</li>
</ul>
