<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Releasedatum: 19.08.2012</h3>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Clientmessage
                <ul>
                    <li>Die abstrakte Klasse zur Definition von Keys ist nun auch als 'abstract' definiert</li>
                </ul>
            </li>
            <li>
                Log
                <ul>
                    <li>Fehler bei der Installation des Paketes behoben durch die falsche Angabe an Spalten beim Übertragen der Logdaten in die neue Tabellenstruktur</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
