<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3></h3>
<ul>
    <li></li>
</ul>
<h3>Datenbankstrukturen der Pakete verwalten</h3>
<ul>
    <li>Jedes Paket wird mit seiner Versionsnummer in der Datenbank gespeichert</li>
    <li>
        Wenn Pakete hinzugefügt oder geupdated werden kann man die Datenbankstruktur mit der '/install.php' updaten
<pre>$logicDatabase = new DragonX_Storage_Logic_Database();
$logicDatabase-&gt;installPackages();</pre>
    </li>
    <li>Die Pakete müssen dafür Plugins der Install Schnittstelle bereit stellen</li>
    <li>
        Das Plugin bekommt die Version des Paketes das bisher verwendet wurde und kann somit auf seine aktuelle Version updaten
<pre>class %packagenamespace%_%packagename%_Plugin_%pluginname%
    implements DragonX_Storage_Plugin_Install_Interface
{
    public function getInstall($version = '0.0.0')
    {
        $sqlstatements = array();
        if (version_compare($version, '1.0.0', '&lt;')) {
            $sqlstatements[] = "%sql%";
        }
        return $sqlstatements;
    }
}</pre>
    </li>
    <li>Die Logikklasse Database speichert danach alle Pakete mit ihren aktuellen Versionsnummer in der Datenbank für das nächste Update</li>
</ul>