<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Download der Projektvorlage</h3>
<ul>
    <li>Über den Download Button der Startseite auf den Downloadbereich gelangen</li>
    <li>Von den verfügbaren Downloads die Projektvorlage downloaden und entpacken</li>
</ul>
<h3>Einrichtung DragonJsonServer</h3>
<ul>
    <li>Von den verfügbaren Downloads den DragonJsonServers downloaden</li>
    <li>Diese in das Verzeichnis 'dragonjsonserver' der Projektvorlage entpacken</li>
    <li>Alternativ zum Download kann mit Subversion auch ein External auf den aktuellen Branch verwendet werden</li>
</ul>
<h3>Einrichtung Zend Framework</h3>
<ul>
    <li>Aktuelle Version des <a title="Externer Link, Inhalt zuletzt geprüft am 14.09.2012" href="http://framework.zend.com/downloads/latest#ZF1">Zend Frameworks 1</a> downloaden</li>
    <li>Diese in das Verzeichnis 'library' der Projektvorlage entpacken</li>
    <li>Alternativ zum Download kann mit Subversion auch ein External auf die aktuelle Version verwendet werden</li>
</ul>
<h3>Einstellung der Datenbank</h3>
<ul>
    <li>
        Erstellen der Konfigurationsdatei '/config/dragonx/storage/database.php' durch Umbenennen und Anpassen der 'database.php.template' Datei
<pre>return array(
    'adapter' =&gt; '%adapter%',
    'config' =&gt; array(
        'host' =&gt; '%host%',
        'username' =&gt; '%username%',
        'password' =&gt; '%password%',
        'dbname' =&gt; '%dbname%',
    ),
);</pre>
    </li>
</ul>
<h3>Upload und Test des Projektes</h3>
<ul>
    <li>Die Projektvorlage samt Zend Framework und DragonJsonServer auf den Server uploaden</li>
    <li>Domain (oder Subdomain) muss auf 'dragonjsonserver/public' geleitet werden</li>
    <li>Aufruf der '/install.php' sollte alle notwendigen Datenbanktabellen aller eingebunden Pakete erstellen</li>
    <li>Aufruf der '/index.php' sollte die Startseite der Homepage anzeigen</li>
    <li>Aufruf von '/dragonjsonclient' sollte den DragonJsonClient mit den Services aus der SMD anzeigen</li>
    <li>Request absenden beim DragonJsonClient (Namensraum Dragon.Application.Service.Application, Methode getApplication) sollte Anwendungsdaten zurückgeben</li>
</ul>
<p>Bei Problemen und Fragen sende eine E-Mail an: firststeps@dragonjsonserver.de</p>
