<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<ul>
    <li>Zeigt standardmäßig auf http://%servername%/jsonrpc2.php</li>
    <li>Holt sich per GET die SMD und baut damit die GUI auf</li>
    <li>Services werden in Namensraum (Klassenname) und Methode (Methodenname) unterteilt</li>
    <li>Parameter die für den Service benötigt werden werden als Argumentfelder angelegt</li>
    <li>Sendet Anfragen per POST und versucht die Antwort als Json anzuzeigen</li>
    <li>Lässt sich auch unabhängig von DragonJsonServer verwenden für Json Server die SMD unterstützen</li>
</ul>
