<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Keine Verwendung von Zend_Acl</h3>
<ul>
    <li>Es wird die Struktur von Ressourcen und Rollen wie bei Zend_Acl verwendet</li>
    <li>Zend_Acl selbst bietet keine Datenbankpersistenz und kann somit nicht verwendet werden ohne größere Nachteile zu haben</li>
</ul>
<h3>Struktur von Rollen und Ressourcen</h3>
<a href="<?php echo $this->baseUrl('image/dragonx_acl_structure.png'); ?>">
    <img src="<?php echo $this->baseUrl('image/thumbnail/dragonx_acl_structure.png'); ?>">
</a>
<ul>
    <li>Ressourcen werden für Services und Funktionalitäten der Homepage benötigt</li>
    <li>Ressourcen können in einer Baumstruktur angeordnet werden, höhere Ressourcen beinhalten dabei alle untergeordnete Ressourcen</li>
    <li>Ressourcen können Rollen zugewiesen werden, Rollen können ebenfalls in einer Baumstruktur angeordnet werden, untergeordnete Rollen erben alle Berechtigungen übergeordneter Rollen</li>
    <li>Rollen können Accounts zugewiesen werden wodurch ein Account an Berechtigungen von Ressourcen gelangt</li>
</ul>
