<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<ul>
    <li>-</li>
</ul>
<hr>
<h3>Releasedatum: noch offen</h3>
<h3>Allgemeine Änderungen</h3>
<ul>
    <li>-</li>
</ul>
<h3>Neue Pakete</h3>
<ul>
    <li>
        Namensraum
        <ul>
            <li>Paketname</li>
        </ul>
    </li>
</ul>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        Namensraum
        <ul>
            <li>
                Paketname
                <ul>
                    <li>-</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h3>Homepage</h3>
<ul>
    <li>-</li>
</ul>
<h3>DragonJsonClient</h3>
<ul>
    <li>-</li>
</ul>
<h2>Migration von %oldversion%</h2>
<h3>Benötigt</h3>
<ul>
    <li>-</li>
</ul>
<h3>Optional</h3>
<ul>
    <li>-</li>
</ul>
