<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<form class="well" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'changeidentity'), null, true); ?>" method="post">
    <h2>E-Mail Adresse ändern</h2>
    <label for="newidentity">Neue E-Mail Adresse:</label><input type="email" id="newidentity" name="newidentity"  required="required" />
    <input type="submit" value="E-Mail Adresse ändern" />
</form>
<form class="well" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'changecredential'), null, true); ?>" method="post">
    <h2>Passwort ändern</h2>
    <label for="newcredential">Neues Passwort:</label><input type="password" id="newcredential" name="newcredential"  required="required" />
    <input type="submit" value="Passwort ändern" />
</form>
<?php if (isset($this->recordDeletion)) { ?>
<form class="well" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'deletedeletion'), null, true); ?>" method="post">
    <h2>Accountlöschung zurücksetzen</h2>
    <input type="submit" value="Accountlöschung zurücksetzen" />
</form>
<?php } else { ?>
<form class="well" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'deleteaccount'), null, true); ?>" method="post">
    <h2>Account löschen</h2>
    <input type="submit" value="Account löschen" />
</form>
<?php } ?>