<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Aufbau der Repositoryeinstellungen</h3>
<ul>
    <li>%repositoryname% enthält den eindeutigen Namen des Repositories. Das erste Repository muss den Namen 'application' haben</li>
    <li>
        %repositorypath% enthält den Pfad zum Respository
<pre>return array(
    '%repositoryname%' =&gt; '%repositorypath%',
);</pre>
    </li>
</ul>
<h3>Nutzung mit Application</h3>
<ul>
    <li>Application legt das Objekt der Repository Registry in der Zend Registry unter dem Key 'Dragon_Repository_Registry' ab</li>
    <li>Application bekommt die Repositoryeinstellungen aus der '/config/repositories.php' und gibt diese an die Repository Registry weiter</li>
</ul>
<h3>Klasse Repository Registry</h3>
<ul>
    <li>
        Kann zur Abfrage des Pfades eines Repositories genutzt werden
<pre>$repositoryregistry = Zend_Registry::get('Dragon_Repository_Registry');
$repositorypath = $repositoryregistry-&gt;getRepository('%repositoryname%');</pre>
    </li>
    <li>
        Kann zur Abfrage genutzt werden welche Repositories eingestellt sind
<pre>$repositoryregistry = Zend_Registry::get('Dragon_Repository_Registry');
$repositories = $repositoryregistry-&gt;getRepositories();</pre>
    </li>
</ul>
