<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Vorteile einer Client Server Trennung</h3>
<ul>
    <li>Der Server benötigt keine Anzeigelogik und kann sich auf die Geschäftigslogik konzentrieren</li>
    <li>API lässt sich von verschiedenen Clients nutzen: Browser, MobileApp, Desktop Anwendung</li>
    <li>Client kann sich auf die Anzeige der Benutzeroberfläche konzentrieren und auf das Ausgabemedium optimiert werden</li>
</ul>
<h3>Vorteile von Json als Austauschformat</h3>
<ul>
    <li>Plattform- und Sprachenunabhängig, da weit verbreitet und breit unterstützt</li>
    <li>Kompakter im Vergleich zu XML, dadurch weniger Traffic zwischen Client und Server</li>
    <li>Json ist JavaScript und lässt sich somit einfach und performant für JavaScript Clients nutzen</li>
</ul>
<h3>Architektur des DragonJsonServer</h3>
<a href="<?php echo $this->baseUrl('image/dragonjsonserver.png'); ?>">
    <img src="<?php echo $this->baseUrl('image/thumbnail/dragonjsonserver.png'); ?>">
</a>
<ul>
    <li>Pakete des Dragon Namensraums stellen Funktionalitäten für den JsonServer und die Homepage zur Verfügung</li>
    <li>Pakete des DragonX Namensraums stellen optionale Funktionalitäten zur Verfügung die von Anwendungen genutzt werden können</li>
    <li>Durch die Paket- und Pluginstruktur kann eine Anwendung beliebige Funktionalitäten in eigenen Namensräumen hinzufügen</li>
</ul>
