<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<div class="hero-unit">
	<address>
		<p><?php echo $this->escape($this->configImprint->webmaster); ?></p>
		<p><a href="<?php echo $this->escape($this->configImprint->mailingaddress); ?>"><?php echo $this->escape($this->configImprint->mailingaddress); ?></a></p>
	</address>
</div>
