<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<h4>Administrationsbereich</h4>
<ul>
    <li>Rechteverwaltung mit Einzelrechten, Rollen und Gruppen (Zend_Acl)</li>
</ul>
<h4>Erweiterungen der Accountverwaltung</h4>
<ul>
    <li>Session auch per API ermöglichen, ein Service der einen Sessionhash für einen Account generiert und zurück gibt welcher dann bei jedem Service übergeben werden muss und für eine gewisse Zeit gültig ist statt bei jedem Aufruf Identität und Credential mitzugeben</li>
    <li>Accounteinstellungen bearbeiten: Identity und Passwort ändern, Account löschen</li>
    <li>Für jeden Statuswechsel, also Gast -> registrierter Account -> validierter Account sollen andere Rechte vergeben werden können und für jeden Statuswechsel soll es Plugin Interfaces geben</li>
</ul>
<h4>Homepage</h4>
<ul>
    <li>Bei den Neuigkeiten Pagination unterstützen um nicht alle Neuigkeiten auf einer Seite anzeigen zu müssen</li>
</ul>
<h3>Version 1.3.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Geänderte Pakete</h4>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Account
                <ul>
                    <li>Accounts die neu registriert werden können nun auch validiert werden durch die E-Mail bzw. dem Hash der Validierungsabfrage</li>
                </ul>
            </li>
            <li>
                Storage
                <ul>
                    <li>Die Schnittstelle 'ICondition' wurde erweitert sodass nun auch Datensätze durch Bedingungen aktualisiert/entfernt werden können</li>
                    <li>Die 'RecordList' besitzt nun weitere Filtermethoden zum Entfernen von neuen oder geladenen Records</li>
                    <li>'beginTransaction()' liefert nun ein Boolean zurück mit dem verschachtelte Transaktionen abgefragt werden können</li>
                    <li>'getTablename()' des ZendDbAdapters ist nun öffentlich verfügbar um dynamische SQL Statements zu unterstützen</li>
                    <li>'load()' gibt bei erfolgreichem Laden nun den Record zurück und wenn nicht false</li>
                </ul>
            </li>
            <li>
                Homepage
                <ul>
                    <li>Wenn ein Account für die Homepage eingeloggt ist wird nun die Navigation für den Administrationbereich geladen</li>
                    <li>Der Modulname wird dem Layout mit übergeben sodass das Layout zu den Controllern des jeweiligen Moduls verlinken kann</li>
                    <li>Der abstrakte Controller prüft nun auf einen gültigen Account wenn auf den Administrationsbereich zugegriffen wird und leitet entsprechend auf den Login um wenn kein gültiger Account vorliegt</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h4>Homepage</h4>
<ul>
    <li>
        Trennung der Homepage vom Administrationsbereich
        <ul>
            <li>Eigene Navigation mit der Startseite und dem DragonJsonClient</li>
            <li>Eigene Startseite für spätere Informationen</li>
		    <li>DragonJsonClient bei dem die Identity der Eingabefelder mit der Identity des eingeloggten Profils vorbelegt ist</li>
        </ul>
    </li>
    <li>Das Changelog ist nun unterteilt in Branches und nicht mehr in die einzelnen Versionen</li>
    <li>Der Login nimmt eine Weiterleitung durch den abstrakten Controller entgegen und leitet bei einem erfolgreichen Login auf diese Seite um</li>
</ul>
<h4>JsonClient</h4>
<ul>
    <li>Bietet nun die Möglichkeit Defaultparameter zu setzen die zu jedem Request mit versendet werden</li>
</ul>
<h4>DragonJsonClient</h4>
<ul>
    <li>Bietet nun die Möglichkeit Defaultparameter zu setzen mit welchen die Eingabefelder vorbefüllt werden</li>
</ul>
<h2>Migration vom Branch 1.2</h2>
<h3>Benötigt</h3>
<ul>
    <li>Da die Anwendung nun in die Bereiche Homepage und Administration getrennt wurde müssen auch alle eigenen Controller und Views darauf aufgeteilt werden</li>
    <li>Da 'load()' nun nicht mehr die Storage Engine selbst zurück gibt sondern den Record müssen Verkettungen aufgelöst werden</li>
</ul>
