<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<h4>Administrationsbereich</h4>
<ul>
    <li>Frontend im Administrationsbereich zur Rechteverwaltung mit Einzelrechten und Rollen</li>
</ul>
<h4>Erweiterungen der Accountverwaltung</h4>
<ul>
    <li>Session auch per API ermöglichen, ein Service der einen Sessionhash für einen Account generiert und zurück gibt welcher dann bei jedem Service übergeben werden muss und für eine gewisse Zeit gültig ist statt bei jedem Aufruf Identität und Credential mitzugeben</li>
    <li>Für jeden Statuswechsel, also Gast -> registrierter Account -> validierter Account sollen andere Rechte vergeben werden können</li>
    <li>"Sofort loslegen" Möglichkeit, sodass man einen temporären Account bekommt und weitere Funktionalitäten testen kann bevor man sich damit registriert. Die temporären Accounts sind an die Session gebunden und müssen mit einer E-Mail Adresse und einem Passwort bestätigt werden um sie zu vollwertigen Accounts zu machen</li>
</ul>
<h4>Homepage</h4>
<ul>
    <li>Ressourcenabfrage bei Actions sodass automatisch Ressourcen abgefragt werden und eine FlashMessage ausgegeben und zur Startseite weitergeleitet wird wenn Berechtigungen fehlen. Am ehesten wie bei Services durch eine Annotation an der Action des Controllers</li>
    <li>Zend Translate unterstützen um alle Beschriftungen und Meldungen sowie Zend Locale um alle Datumsangaben der Homepage lokalisiert auszugeben</li>
    <li>Paketabfrage durch die 'isAvailable()' der Package Registry durch die Homepage durchziehen, sodass Funktionalitäten wie Registrierung/Anmeldung deaktiviert werden wenn das Account Paket nicht aktiviert ist und die Homepage bei jeder Paketkonstellation funktionsfähig bleibt</li>
</ul>
<h3>Version 1.4.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Homepage</h4>
<ul>
    <li>Link im Header für Homepage/Administration um zwischen den beiden Bereichen zu wechseln wenn man eingeloggt ist. Dadurch ist der DragonJsonClient im Administrationsbereich unnötig und wurde entfernt</li>
    <li>Update der Twitter Bootstrap Bibliothek auf die aktuelle Version 2.1.0</li>
    <li>Umbenennung der öffentlichen Standardordner von 'image' zu 'img' und von 'javascript' zu 'js'</li>
    <li>Der Name und die E-Mail Adresse im Impressum sind nun per 'address' Tag gekennzeichnet</li>
    <li>Layout aller Formulare angepasst sodass diese ansprechender aussehen</li>
    <li>Layout der Startseite und des Impressums angepasst. Insbesondere auch das Layout der Pagination auf der Startseite für die Neuigkeiten</li>
</ul>
<h4>DragonJsonClient</h4>
<ul>
    <li>Layout des Formulars angepasst sodass diese ansprechender aussehen und zum restlichen Layout des Projektes passt</li>
</ul>
