<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'credential', 'action' => 'reset'), null, true); ?>" method="post">
    <input type="hidden" name="credentialhash" value="<?php echo $this->escape($this->credentialhash); ?>">
    <legend>Passwort zurücksetzen</legend>
    <div class="control-group">
        <label class="control-label" for="newpassword">Neues Passwort:</label>
        <div class="controls">
            <input type="password" id="newpassword" name="newpassword" required="required">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Passwort zurücksetzen</button>
        </div>
    </div>
</form>
