<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<ul>
    <li>Errorhandling erweitern sodass alle Exceptions die man loggt in eine Exceptionlogklasse gehen mit Spalten für Dateinamen usw.</li>
    <li>Errorhandling erweitern sodass alle Exceptions die zum Client gesendet werden auch im Logging und der Exceptiontabelle landen, abgeleitete Exceptionklasse "User" die nicht geloggt werden für "E-Mail ungültig" usw.</li>
    <li>Fehlerbehebung: Reihenfolge der Konfigurationsdateien ist falsch wenn mehrere Repositories existieren. Da muss das Array umgedreht werden entweder einmal wo Librarypaths gemacht werden oder bei den Konfigurationsdateien</li>
    <li>"set_error_handler()" verwenden um einen Error Handler zu registrieren der auftretende PHP Fehler die nicht zum Abbruch eines Skriptes führen loggt und somit die PHP Fehler nicht in der Response landen</li>
    <li>"set_exception_handler()" verwenden um einen Exception Handler zu registrieren der auftretende Ausnahmen außerhalb von Services loggt und somit die Ausnahmen nicht in der Response landen</li>
</ul>
<h3>Version 1.10.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Geänderte Pakete</h4>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Homepage
                <ul>
                    <li>Wenn die Session abgelaufen ist wird nun die richtige Hinweismeldung auf der Homepage angezeigt statt einer Ausnahme</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h4>Homepage</h4>
<ul>
    <li>Wenn eine E-Mail Adresse nicht korrekt ist oder bereits vergeben ist wird dies nun zusammen angezeigt statt getrennt voneinander</li>
</ul>
<h4>JsonClient</h4>
<ul>
    <li>In den Callbackmethoden für einen JsonRequest steht nun das Objekt des JsonRequest selbst unter der Variable "jsonrequest" zur Verfügung</li>
</ul>
