<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<h4>Erweiterungen der Accountverwaltung</h4>
<ul>
    <li>Homepage anpassen auf die neue Accountverwaltung</li>
    <li>Dokumentation und Changelog für die neue Accountverwaltung</li>
</ul>
<h3>Version 1.7.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Neue Pakete</h4>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Emailaddress
                <ul>
                    <li></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h4>Geänderte Pakete</h4>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Account
                <ul>
                    <li>Es ist nun möglich einen eigenen Record für die Accountdaten zu verwenden indem man die Recordklasse 'Application_Account_Record_Account' definiert</li>
                    <li>Anpassungen um einen eigenen Record der Accountdaten zu unterstützen</li>
                    <li>Die Verlinkung eines Accounts mit einer E-Mail Adresse und einem Passwort wurde vom Paket Account getrennt und in das neue Paket Emailaddress ausgelagert</li>
                    <li>Es steht nun eine Pluginschnittstelle zur Verfügung für Plugins die nach dem Laden eines Accounts bei jedem Request aufgerufen werden sollen</li>
                </ul>
            </li>
            <li>
                Acl
                <ul>
                    <li>Anpassungen um einen eigenen Record der Accountdaten zu unterstützen</li>
                </ul>
            </li>
            <li>
                Application
                <ul>
                    <li>Die abstrakte Eigenschaftsklasse wurde umbenannt von 'DragonX_Application_Accessor' in 'DragonX_Application_Accessor_Abstract'</li>
                    <li>Es wird nun das Befüllen von Arrays sowohl beim einzelnen Setzen als auch das Befüllen aus einem Array mit '_' unterstützt</li>
                </ul>
            </li>
            <li>
                Clientmessage
                <ul>
                    <li>Umstellung der Records für die beiden Clientmessagequellen auf die neue Recordklasse mit einem Erstellungszeitpunkt</li>
                </ul>
            </li>
            <li>
                Cronjob
                <ul>
                    <li>Umstellung der Records für die Cronjobs auf die neue Recordklasse mit einem Erstellungs- und Änderungszeitpunkt</li>
                    <li>Es ist nun möglich einzelne Cronjobs gezielt auszuführen auch wenn sie zeitlich noch nicht ausgeführt werden sollen</li>
                </ul>
            </li>
            <li>
                Log
                <ul>
                    <li>Umstellung der Records für die Logeinträge auf die neue Recordklasse mit einem Erstellungszeitpunkt</li>
                </ul>
            </li>
            <li>
                Storage
                <ul>
                    <li>Abstrakte Recordklassen hinzugefügt die ein Erstellungs- und Änderungszeitpunkt definieren. Davon abgeleitete Records erhalten beim Speichern in eine Storage Engine automatisch die Zeitpunkte</li>
                    <li>Umstellung der Records für die Pakete auf die neuen Recordklassen sodass nun ersichtlich ist wann ein Paket hinzugefügt und zuletzt aktualisiert wurde</li>
                    <li>
                        Die Storage Engine wurde erweitert sodass mehrere Datenbankadapter und Storage Engines definiert werden können
                        <ul>
		                    <li>Es ist nun möglich in der Konfigurationsdatei '/config/dragonx/storage/database.php' mehrere Datenbankverbindungen zu definieren die in verschiedene Keys der Zend Registry hinterlegt werden</li>
		                    <li>Es ist nun möglich in der Konfigurationsdatei '/config/dragonx/storage/engine.php' mehrere Storage Engines zu definieren die in verschiedene Keys der Zend Registry hinterlegt werden</li>
		                    <li>Installationsplugins und deren Verwaltung wurde erweitert sodass man die Datenbankstruktur verschiedener Datenbanken damit verwalten kann</li>
		                </ul>
                    </li>
                    <li>Es wird nun das Speichern von Records mit Arrays unterstützt und mit '_' in den Spaltennamen umgesetzt</li>
                    <li>Der Datenbankname für die Storage Engine steht nun mit 'getDatabasename()' zur Verfügung</li>
                    <li>Der Adapter für die Storage Engine steht nun mit 'getAdapter()' auch nach aussen zur Verfügung</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h4>Allgemein</h4>
<ul>
    <li>Die Konstante 'APPLICATION_PATH' wird in der 'bootstrap.php' definiert wenn das Repository 'application' vorhanden ist</li>
</ul>
<h4>JsonClient</h4>
<ul>
    <li>Unterstützt nun Htaccess Authentifizierung durch die Methode 'setAuthenticate()'</li>
</ul>
<h4>DragonJsonClient</h4>
<ul>
    <li>Unterstützt nun Defaultwerte aus der SMD und trägt diese in die Eingabefelder ein falls noch keine selbst eingetragenen Werte zur Verfügung stehen</li>
    <li>Es werden nun auch die Anwendungsdaten der JsonClient Bibliothek mit Name und Version angezeigt</li>
</ul>
<h2>Migration vom Branch 1.6</h2>
<h3>Benötigt</h3>
<div class="alert alert-warning">Achtung: Durch die Trennung der Pakete Account und Emailaddress muss vor der Ausführung der 'install.php' das Paket Emailaddress hinzugefügt werden, da sonst alle Verknüpfungen zu den Accounts verloren gehen. Ebenfalls aktiviert werden muss das Paket Account aus dem Application Namensraum, da sind die Accounts verloren gehen.</div>
<ul>
    <li>Durch die Umstellung der beiden Clientmessagequellen auf die neue Recordklasse mit einem Erstellungszeitpunkt erhält der Client nun bei jeder Clientmessage ihren Erstellungszeitpunkt als 'created' statt als 'timestamp'</li>
    <li>Durch die Umbennung der Eigenschaftsklasse 'DragonX_Application_Accessor' in 'DragonX_Application_Accessor_Abstract' müssen alle eigenen davon abgeleiteten Klassen angepasst werden</li>
    <li>Clients die bereits die Accountverwaltung genutzt haben müssen angepasst werden auf die neuen Services</li>
</ul>
