<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<ul>
    <li>Zend Translate unterstützen um alle Beschriftungen und Meldungen sowie Zend Locale um alle Datumsangaben der Homepage lokalisiert auszugeben</li>
    <li>Frontend im Administrationsbereich zur Rechteverwaltung mit Einzelrechten und Rollen</li>
    <li>Für jeden Statuswechsel, also Gast -&gt; registrierter Account -&gt; validierter Account sollen andere Rechte vergeben werden können</li>
	<li>Pluginregistry soll Abhängigkeiten unterstützen. Ein Plugin soll per Interface Abhängigkeiten zu anderen Plugins definieren können und diese werden in der richtigen Reihenfolge in der Registry hinterlegt</li>
    <li>Fehlerbehandlung überarbeiten, Exceptions loggen und ausführlicher werfen um Fehler nachvollziehen zu können, vor allem falsche SQL Statements</li>
    <li>Session von Account trennen sodass man die Session in eine andere Storage Engine verschieben kann</li>
    <li>"set_error_handler()" verwenden um einen Error Handler zu registrieren der auftretende PHP Fehler die nicht zum Abbruch eines Skriptes führen loggt und somit die PHP Fehler nicht in der Response landen</li>
    <li>Accountauswahl im DragonJsonClient sodass man zwischen Abfragen einfacher zwischen mehreren Accounts (mit Sessionhash und beliebig anderen Parametern) wechseln kann</li>
    <li>Die Startseite für den Administrationsbereich variable machen sodass man einstellen kann welcher Controller/Actions nach dem Login aufgerufen werden soll</li>
</ul>
<h3>Version 1.9.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Geänderte Pakete</h4>
<ul>
    <li>
        Dragon
        <ul>
            <li>
                Package
                <ul>
                    <li>Es gibt nun einen Service der die Einstellungen der "/config/packagenamespaces.php" an den Client zurück gibt. Somit gibt es für den Client eine einfachere Möglichkeit seine Features darauf anzupassen was beim Server aktiviert/deaktiviert ist im Gegensatz zur Abfrage der SMD</li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        DragonX
        <ul>
            <li>
                Log
                <ul>
                    <li>Es ist nun per Einstellungsdatei möglich die Storage Engine für die Logdaten zu bestimmen</li>
                </ul>
            </li>
            <li>
                Storage
                <ul>
                    <li>Eine Kopie eines Records durch "clone()" erstellt nun ein neues Objekt ohne die ID des anderen Objektes sodass auch in der Datenbank eine Kopie erstellt wird</li>
                    <li>Der Konstruktor eines Records hat nun einen zweiten Parameter der bestimmt ob die ID des übergebenen Arrays/Records bei der Übernahme der Daten resettet wird oder nicht</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h4>Homepage</h4>
<ul>
    <li>Die Subnavigation highlightet nun die Links in der Navigation richtig auch wenn die Actionnamen wie im Changelog numerisch sind (kein Highlight der Version 1.1 wenn die Version 1.10 aktiv ist)</li>
</ul>
<h2>Migration vom Branch 1.8</h2>
<h3>Benötigt</h3>
<ul>
    <li>Das Verhalten der Records hat sich geändert wenn man diese bisher mit einem "toArray()" in einen anderen Record übergeben hat. Vorher wurde die ID beibehalten, nun ist es Abhängig vom zweiten Parameter und das Standardverhalten entfernt die ID. Daher muss überall wo die ID beibehalten werden soll und deswegen ein "toArray()" verwendet wurde der zweite Parameter mit "false" angegeben werden</li>
</ul>
