<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<?php
if ($this->pageCount > 0) {
	if (isset($this->previous)) {
		echo '<a href="?page=' . $this->previous . '">&lt; Vorherige Seite</a>';
	} else {
		echo '&lt; Vorherige Seite';
	}
	echo ' | ';

	foreach ($this->pagesInRange as $page) {
		if ($page == $this->current) {
            echo $page;
		} else {
		    echo '<a href="?page=' . $page . '">' . $page . '</a>';
		}
		echo ' | ';
	}

    if (isset($this->next)) {
        echo '<a href="?page=' . $this->next . '">Nächste Seite &gt;</a>';
    } else {
        echo 'Nächste Seite &gt;';
    }
}
?>
