<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Releasedatum: 23.08.2012</h3>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        Dragon
        <ul>
            <li>
                Json
                <ul>
                    <li>Fehler beim Setzen des HTTP Header bei Multirequests. Dieser wird nun richtig gesetzt</li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        DragonX
        <ul>
            <li>
                Clientmessage
                <ul>
                    <li>Es besteht nun die Möglichkeit das Senden der Clientnachrichten durch Belegung des 'timestamp' mit -1 zu deaktivieren</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h3>JsonClient</h3>
<ul>
    <li>Sendet und bearbeitet nun auch Multirequests richtig wenn Clientnachrichten aktiviert sind. Diese werden nur beim letzten Request angefordert</li>
</ul>
