<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<ul>
    <li>"set_error_handler()" verwenden um einen Error Handler zu registrieren der auftretende PHP Fehler die nicht zum Abbruch eines Skriptes führen loggt und somit die PHP Fehler nicht in der Response landen</li>
    <li>Frontend im Administrationsbereich zur Rechteverwaltung mit Einzelrechten und Rollen</li>
    <li>Für jeden Statuswechsel, also Gast -&gt; registrierter Account -&gt; validierter Account sollen andere Rechte vergeben werden können</li>
</ul>
<h3>Version 1.9.0</h3>
<h4>Releasedatum: noch offen</h4>
