<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'account', 'action' => 'login'), null, true); ?>" method="post">
    <?php if (isset($this->redirect)) { echo '<input type="hidden" name="redirect" value="' . $this->escape($this->redirect) . '">'; } ?>
    <fieldset>
	    <legend>Anmelden</legend>
	    <div class="control-group">
	        <label class="control-label" for="emailaddress">E-Mail Adresse:</label>
	        <div class="controls">
	            <input type="email" id="emailaddress" name="emailaddress" required="required">
	        </div>
	    </div>
	    <div class="control-group">
	        <label class="control-label" for="password">Passwort:</label>
	        <div class="controls">
	            <input type="password" id="password" name="password"  required="required">
	        </div>
	    </div>
	    <div class="control-group">
	        <div class="controls">
	            <button type="submit" class="btn">Anmelden</button>
	            <a href="<?php echo $this->url(array('controller' => 'credential', 'action' => 'showrequest'), null, true); ?>">Passwort vergessen</a>
	        </div>
	    </div>
	</fieldset>
</form>
