<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Releasedatum: 20.08.2012</h3>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        DragonX
        <ul>
            <li>
                Account
                <ul>
                    <li>Fehler behoben bei der Ermittlung ob ein Service einen eingeloggten Account benötigt wenn der Service keine API Dokumentation besitzt zur Ermittlung der Annotation</li>
                    <li>Fehlende API Dokumentation für die Passwort vergessen Services nachgetragen</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h3>Homepage</h3>
<ul>
    <li>Das JavaScript für Bootstrap wird nun nur noch einmal am Ende des Layouts geladen und nicht mehr doppelt</li>
</ul>
