<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Noch geplante Änderungen</h3>
<ul>
    <li>-</li>
</ul>
<hr>
<h3>Releasedatum: noch offen</h3>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        Dragon
        <ul>
            <li>
                Json
                <ul>
                    <li>Wenn man eigene Instanzen von Dragon_Json_Server_Request erstellt ist die JsonRPC Version nun standardmäßig 2.0</li>
                    <li>Bei der automatischen Ausgabe von Responses eines Multirequests wird nun standardmäßig der HTTP Header des letzten Responses gesendet</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
<h3>Homepage</h3>
<ul>
    <li>Der Footer hat nun keinen Freiraum mehr nach unten wenn die Fensterbreiter kleiner als 980px ist</li>
</ul>
