<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Releasedatum: noch offen</h3>
<h3>Geänderte Pakete</h3>
<ul>
    <li>
        Dragon
        <ul>
            <li>
                Application
                <ul>
                    <li>Bei Eigenschaftsklassen wird nun ein 'unset()' auf ein Attribut richtig unterstützt indem es das Attribut auf NULL setzt</li>
                </ul>
            </li>
        </ul>
    </li>
    <li>
        DragonX
        <ul>
            <li>
                Storage
                <ul>
                    <li>Fehler behoben beim Laden von einzelnen Records oder RecordLists wodurch die ID der Records nicht korrekt auf NULL gesetzt wurde und es zu Fehlermeldungen kam</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
