<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Administrationsbereich</h3>
<ul>
    <li>Registrierung, Login (Zend_Auth) und Passwort vergessen</li>
    <li>Rechteverwaltung mit Einzelrechten, Rollen und Gruppen (Zend_Acl)</li>
    <li>Accounteinstellungen bearbeiten: Identity und Passwort ändern, Account löschen</li>
</ul>
<h3>Neuigkeiten und Newsletter</h3>
<ul>
    <li>Neuigkeiten in der Datenbank speichern</li>
    <li>Verwaltung von Neuigkeiten im Administrationsbereich (Neuigkeiten anlegen, veröffentlichen, ändern und entfernen)</li>
    <li>Newsletter An-/Abmeldung, Neuigkeiten werden bei der Veröffentlichung als Newsletter versendet</li>
</ul>
<h3>Paketverwaltung</h3>
<ul>
    <li>Pakete und deren Plugins und Services an-/abschalten</li>
    <li>Einstellungen von Paketen bearbeiten</li>
    <li>Abhängigkeiten zwischen Paketen anzeigen und abhängige Pakete mit an-/abschalten</li>
    <li>Update von Paketen</li>
</ul>
<h3>Monitoring</h3>
<ul>
    <li>
        Highcharts für Zeiträume (Verwendung von <a href="http://www.highcharts.com">http://www.highcharts.com</a>) anzeigen für
        <ul>
            <li>Anzahl Requests</li>
            <li>Anzahl Logeinträge</li>
            <li>Anzahl Fehlereinträge</li>
            <li>Anzahl Registrierungen</li>
        </ul>
    </li>
    <li>Anzeige der letzten Requests mit Eingabeparametern und Ausgabe</li>
</ul>
<h3>Erweiterungen des DragonJsonClients</h3>
<ul>
    <li>Multirequests unterstützen durch Hinzufügen (am Ende oder nach anderen Requests der Queue), Ändern und Entfernen von Einzelrequests</li>
    <li>Dauerhafte Speicherung von Requests zum Laden, Ändern und erneuten Ausführen</li>
    <li>Export von Einzel- und Multirequests im jQuery Format zur Einbindung in einen eigenen Client</li>
</ul>
<h3>Neue Schnittstellen an den Server</h3>
<ul>
    <li>XML RPC</li>
    <li>Websocket</li>
</ul>
