<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<h3>Version 1.7.0</h3>
<h4>Releasedatum: noch offen</h4>
<h4>Projektvorlage</h4>
<ul>
    <li>Einstellungsdatei '/config/packagenamespaces.php' erweitert um das neue Paket Emailaddress und Übernahme der Änderungen an dem Paket Account</li>
</ul>
