<?php
/**
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled with this
 * package in the file LICENSE.txt. It is also available through the
 * world-wide-web at this URL: http://dragonjsonserver.de/license. If you did
 * not receive a copy of the license and are unable to obtain it through the
 * world-wide-web, please send an email to license@dragonjsonserver.de. So we
 * can send you a copy immediately.
 *
 * @copyright Copyright (c) 2012 DragonProjects (http://dragonprojects.de)
 * @license http://framework.zend.com/license/new-bsd New BSD License
 * @author Christoph Herrmann <developer@dragonjsonserver.de>
 */
?>
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
        <title>
            <?php
                echo $this->configApplication->name;
                if (isset($this->configNavigation->header->{$this->controllername})) {
                	$navigation = $this->configNavigation->header->{$this->controllername};
                    if (!$navigation instanceof Zend_Config) {
                        $navigation = new Zend_Config(array('label' => $navigation));
                    }
                    echo ' - ' . $navigation->label;
                }
                if (isset($this->configNavigation->footer->{$this->controllername})) {
                    $navigation = $this->configNavigation->footer->{$this->controllername};
                    if (!$navigation instanceof Zend_Config) {
                        $navigation = new Zend_Config(array('label' => $navigation));
                    }
                    echo ' - ' . $navigation->label;
                }
            ?>
        </title>
        <link rel="alternate" type="application/rss+xml" title="RSS" href="<?php echo $this->baseUrl('feed.php'); ?>" />
        <link href="<?php echo $this->baseUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('css/bootstrap-responsive.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('css/layout.css'); ?>" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <?php
                    if (isset($this->recordAccount)) {
	                    echo '<ul class="nav">';
                        if ($this->modulename == 'administration') {
                            echo '<li><a href="' . $this->url(array('module' => 'homepage'), null, true) .'">Homepage</a></li>';
                        } else {
                            echo '<li><a href="' . $this->url(array('module' => 'administration'), null, true) .'">Administration</a></li>';
                        }
                        echo '</ul>';
                    }
                    ?>
                    <span class="brand"><?php echo $this->configApplication->name . ' ' . $this->configApplication->version; ?></span>
                    <ul class="nav">
                        <?php
                        foreach ($this->configNavigation->header as $controller => $navigation) {
                        	if (!$navigation instanceof Zend_Config) {
                        		$navigation = new Zend_Config(array('label' => $navigation));
                        	}
                        	if (isset($navigation->resource) && !in_array($navigation->resource, $this->resources)) {
                                continue;
                        	}
                            echo '<li' . ($this->controllername == $controller ? ' class="active"' : '') . '><a href="' . $this->url(array('module' => $this->modulename, 'controller' => $controller), null, true) . '">' . $navigation->label . '</a></li>';
                        }
                        ?>
                    </ul>
                    <?php if (Zend_Registry::get('Dragon_Package_Registry')->isAvailable('DragonX', 'Account')) { ?>
                    <div class="btn-group pull-right">
                        <?php if (isset($this->recordAccount) && isset($this->recordAccount->identity)) { ?>
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="">
                            <?php echo $this->recordAccount->identity; ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'showedit'), null, true); ?>">Bearbeiten</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'logout'), null, true); ?>">Abmelden</a></li>
                        </ul>
                        <?php } elseif (isset($this->recordAccount)) { ?>
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="">
                            Temporäres Profil
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'showsave'), null, true); ?>">Speichern</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'administration', 'controller' => 'account', 'action' => 'logout'), null, true); ?>">Abmelden</a></li>
                        </ul>
                        <?php } else { ?>
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="">
                            Profil
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'showlogin'), null, true); ?>">Anmelden</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'temporary'), null, true); ?>">Sofort loslegen</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'showregister'), null, true); ?>">Registrieren</a></li>
                        </ul>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="container">
            <?php
                if (isset($this->recordAccount) && !isset($this->recordAccount->identity)) {
                    $this->messages[] = '<div class="alert">Das Profil ist nur temporär und wird durch die Abmeldung oder Auslauf der Session wieder entfernt. Speichern sie das Profil um es dauerhaft verfügbar zu machen</div>';
                }
                if (isset($this->recordDeletion)) {
                    $this->messages[] = '<div class="alert">Profil wurde zum Löschen eingetragen und wird nach dem ' . date('d.m.Y', $this->recordDeletion->timestamp) . ' gelöscht</div>';
                }
                foreach ($this->messages as $message) {
                	echo $message;
                }
            ?>
            <?php echo $this->layout()->content ?>
            <footer>
                <div class="navbar navbar-inverse navbar-fixed-bottom">
                    <div class="navbar-inner">
                        <div class="container">
                            <span class="brand"><?php echo $this->configApplication->copyright; ?></span>
                            <ul class="nav">
                                <?php
                                foreach ($this->configNavigation->footer as $controller => $navigation) {
                                	echo '<li' . ($this->controllername == $controller ? ' class="active"' : '') . '><a href="' . $this->url(array('module' => $this->modulename, 'controller' => $controller), null, true) . '">' . $navigation . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <script src="<?php echo $this->baseUrl('js/bootstrap.min.js'); ?>"></script>
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </body>
</html>
